function config = summarizeMorphStructures(sessionPath)
    sessionPath = string(sessionPath); 
    config = struct(...
        'Sq1', find(contains(sessionPath, 'Sq1')),...
        'Sq2', find(contains(sessionPath, 'Sq2')),...
        'Sq3', find(contains(sessionPath, 'Sq3')),...
        'G3', find(contains(sessionPath, 'G3')),...
        'G2', find(contains(sessionPath, 'G2')),...
        'G1', find(contains(sessionPath, 'G1')));



    
        
    
        
    
        